name: Run Pytest with Coverage

on:
  push:
    branches:
      - master
      - new_branch

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=${{ github.workspace }}/src" >> $GITHUB_ENV


    - name: Run mypy to validate type hints assignments
      run: |
        mypy src/TC1.py


    - name: Run Pytest with Coverage
      run: |
        pytest --verbose --cov=src/. --cov-report=term-missing --cov-report=html